### PR TITLE
OCPBUGS-16546: remove dependency elazarl/goproxy

### PR DESCRIPTION
**Pull request by SalDaniele**
This commit updates a number of dependencies, namely k8s.io/apimachinery, in order to remove the dependency on the outdated package github.com/elazarl/goproxy.

The replace of containernetworking/cni v0.8.1 is also removed, as latest cni is required to remove this dependency.

### CODE REVIEW

**Comment by SchSeba** [comment]
/hold

@SalDaniele this is a cherry-pick from u/s?

**Comment by SalDaniele** [comment]
Yes, https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/499

**Comment by SchSeba** [comment]
Hi @SalDaniele can you please just run git merge? so we maintain the sync between the repos please

**Comment by SalDaniele** [comment]
Hi @SchSeba yes, just submitted a new PR to merge from US

**Comment by SalDaniele** [comment]
This can be closed, added in #79

**Pull request closed without merging**
