### PR TITLE
Bug 1746661: glide update (#174)

### PR DESCRIPTION
**Pull request by zshi-redhat**
update grpc to v1.23.0

### CODE REVIEW

**Comment by knobunc** [comment]
Does this have a corresponding master change (and bug?).  Should it?

**Comment by zshi-redhat** [comment]
> Does this have a corresponding master change (and bug?). Should it?

@knobunc This [PR](https://github.com/openshift/sriov-network-device-plugin/pull/18) is for master change, the corresponding bugzilla is [1746650](https://bugzilla.redhat.com/show_bug.cgi?id=1746650)

**Comment by knobunc** [comment]
If someone can approve this too, it will be ready for next week.

**Pull request merged**
