### PR TITLE
4.7 update 2020-11-19

### PR DESCRIPTION
**Pull request by zshi-redhat**
4.7 update:
1. add no-iommu vfio-pci support
2. update with NPWG git URLs
3. fix issue that DP pod cannot receive process signals

### CODE REVIEW

**Comment by pliurh** [comment]
> add no-iommu vfio-pci support

Shall we also support this in the sriov operator?

**Comment by zshi-redhat** [comment]
> > add no-iommu vfio-pci support
> 
> Shall we also support this in the sriov operator?

We won't, this is an unsafe mode and only used for VM case as a temp solution.

**Comment by zshi-redhat** [comment]
> > > add no-iommu vfio-pci support
> > 
> > 
> > Shall we also support this in the sriov operator?
> 
> We won't, this is an unsafe mode and only used for VM case as a temp solution.

Chat with @atyronesmith , this is currently done by applying a MC, in theory we can do it also in sriov-operator, not sure how feasible it would be, e.g. whether we can add it without changing API or introducing another device type.

@atyronesmith will take a look.

The sriov opeartor change should not block this device plugin update.

**Comment by atyronesmith** [comment]
> > > > add no-iommu vfio-pci support
> > > 
> > > 
> > > Shall we also support this in the sriov operator?
> > 
> > 
> > We won't, this is an unsafe mode and only used for VM case as a temp solution.
> 
> Chat with @atyronesmith , this is currently done by applying a MC, in theory we can do it also in sriov-operator, not sure how feasible it would be, e.g. whether we can add it without changing API or introducing another device type.
> 
> @atyronesmith will take a look.
> 
> The sriov opeartor change should not block this device plugin update.

A shell script similar to load-kmod.sh could be used.

```shell
#!/bin/sh

configfile="/etc/modprobe.d/vfio-noiommu.conf"

chroot /host/ cat > $configfile <<- "EOF"
options vfio enable_unsafe_noiommu_mode=1
EOF
```

**Pull request merged**
